version: 0.2

phases:
  install:
    commands:
  pre_build:
    commands:
  build:
    commands:
      - echo Entering build phase...
      - echo Build started on `date`
      - ./gradlew check jmhClasses smokeTest distZip
  post_build:
    commands:
artifacts:
  files:
    - 'app/build/distributions/app.zip'
    - 'app/src/main/resources/ax9k_smoke_test.csv'
    - 'scripts/*.sh'
    - 'scripts/*.txt'
    - 'appspec.yml'
    - 'Dockerfile'
  discard-paths: yes

